# Generated by Django 6.0.1 on 2026-02-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
                ('categoryStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test_category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productDesc', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
                ('productColor', models.CharField(blank=True, max_length=20, null=True)),
                ('productStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test_product',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceDescription', models.TextField()),
                ('servicePrice', models.FloatField()),
                ('serviceStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'test_service',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField()),
                ('studentCity', models.CharField(max_length=40)),
                ('studentEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'test_student',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test.client')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'Reading'), ('sports', 'Sports'), ('music', 'Music')], max_length=50)),
                ('studentPhone', models.CharField(max_length=15)),
                ('studentAddress', models.CharField(max_length=255)),
                ('studentGender', models.CharField(max_length=10)),
                ('studentDOB', models.DateField()),
                ('student', models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='test.student')),
            ],
            options={
                'db_table': 'test_studentprofile',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.project')),
            ],
        ),
    ]
