# Generated by Django 6.0.1 on 2026-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentage', models.IntegerField()),
                ('studentcity', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
