# Generated by Django 6.0.1 on 2026-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_studentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productDesc', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentage',
            new_name='studentAge',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentcity',
            new_name='studentCity',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentemail',
            new_name='studentEmail',
        ),
    ]
