# Generated by Django 6.0.1 on 2026-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_rename_studentage_student_studentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcolor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productstatus',
            field=models.BooleanField(default=True),
        ),
    ]
