# Generated by Django 6.0.1 on 2026-02-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productstatus',
            new_name='productStatus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productcolor',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('studentHobbies', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('swimming', 'Swimming')], max_length=50)),
                ('studentPhone', models.CharField(max_length=15)),
                ('studentAddress', models.CharField(max_length=255)),
                ('studentGender', models.CharField(max_length=10)),
                ('studentDOB', models.DateField()),
                ('studentId', models.OneToOneField(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
